-- ==========================================
-- 0. CLEANUP (DROP EXISTING TABLES & USERS)
-- ==========================================
DROP FUNCTION IF EXISTS GET_PUBLIC_AVAILABILITY(DATE, DATE);
DROP TABLE IF EXISTS NOTIFICATIONS CASCADE;
DROP TABLE IF EXISTS ADMIN_NOTES CASCADE;
DROP TABLE IF EXISTS BOOKINGS CASCADE;
DROP TABLE IF EXISTS INQUIRIES CASCADE;
DROP TABLE IF EXISTS CLIENTS CASCADE;

-- Remove existing admin user if they exist to avoid conflicts
DO $$
BEGIN
    DELETE FROM auth.identities WHERE email = 'jombenitez96@gmail.com';
    DELETE FROM auth.users WHERE email = 'jombenitez96@gmail.com';
END $$;


-- ==========================================
-- 1. SETUP EXTENSIONS & TABLES
-- ==========================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE CLIENTS (
    ID              UUID DEFAULT uuid_generate_v4() PRIMARY KEY
,   FULL_NAME       TEXT NOT NULL
,   EMAIL           TEXT
,   PHONE           TEXT
,   CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
,   UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE INQUIRIES (
    ID              UUID DEFAULT uuid_generate_v4() PRIMARY KEY
,   CLIENT_ID       UUID NOT NULL REFERENCES CLIENTS(ID) ON DELETE CASCADE
,   EVENT_TYPE      TEXT NOT NULL
,   EVENT_DATE      DATE NOT NULL
,   START_TIME      TIME NOT NULL
,   END_TIME        TIME NOT NULL
,   LOCATION        TEXT
,   PROJECT_NOTES   TEXT
,   STATUS          TEXT NOT NULL DEFAULT 'PENDING'
,   SOURCE          TEXT NOT NULL DEFAULT 'WEBSITE'
,   CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
,   UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE BOOKINGS (
    ID              UUID DEFAULT uuid_generate_v4() PRIMARY KEY
,   INQUIRY_ID      UUID REFERENCES INQUIRIES(ID) ON DELETE SET NULL
,   CLIENT_ID       UUID NOT NULL REFERENCES CLIENTS(ID) ON DELETE CASCADE
,   EVENT_DATE      DATE NOT NULL
,   START_TIME      TIME NOT NULL
,   END_TIME        TIME NOT NULL
,   LOCATION        TEXT
,   STATUS          TEXT NOT NULL DEFAULT 'CONFIRMED'
,   CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
,   UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE ADMIN_NOTES (
    ID              UUID DEFAULT uuid_generate_v4() PRIMARY KEY
,   INQUIRY_ID      UUID NOT NULL REFERENCES INQUIRIES(ID) ON DELETE CASCADE
,   ADMIN_ID        UUID NOT NULL REFERENCES auth.users(ID) ON DELETE CASCADE
,   NOTE            TEXT NOT NULL
,   CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
,   UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE NOTIFICATIONS (
    ID              UUID DEFAULT uuid_generate_v4() PRIMARY KEY
,   ADMIN_ID        UUID NOT NULL REFERENCES auth.users(ID) ON DELETE CASCADE
,   TYPE            TEXT NOT NULL
,   TITLE           TEXT NOT NULL
,   MESSAGE         TEXT NOT NULL
,   IS_READ         BOOLEAN DEFAULT FALSE
,   CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ==========================================
-- 2. ENABLE ROW LEVEL SECURITY (RLS)
-- ==========================================
ALTER TABLE CLIENTS ENABLE ROW LEVEL SECURITY;
ALTER TABLE INQUIRIES ENABLE ROW LEVEL SECURITY;
ALTER TABLE BOOKINGS ENABLE ROW LEVEL SECURITY;
ALTER TABLE ADMIN_NOTES ENABLE ROW LEVEL SECURITY;
ALTER TABLE NOTIFICATIONS ENABLE ROW LEVEL SECURITY;


-- ==========================================
-- 3. PUBLIC POLICIES
-- ==========================================
-- ALLOW ANYONE TO SUBMIT A NEW CLIENT (DURING INQUIRY FLOW)
CREATE POLICY "ALLOW PUBLIC INSERT CLIENTS" ON CLIENTS
    FOR INSERT 
    WITH CHECK (true);

-- ALLOW ANYONE TO SUBMIT A NEW INQUIRY
CREATE POLICY "ALLOW PUBLIC INSERT INQUIRIES" ON INQUIRIES
    FOR INSERT 
    WITH CHECK (
        STATUS = 'PENDING' 
        AND SOURCE = 'WEBSITE'
    );


-- ==========================================
-- 4. ADMIN POLICIES
-- ==========================================
-- ADMINS (AUTHENTICATED USERS) HAVE FULL ACCESS TO ALL TABLES
CREATE POLICY "ALLOW AUTHENTICATED ALL CLIENTS" ON CLIENTS FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "ALLOW AUTHENTICATED ALL INQUIRIES" ON INQUIRIES FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "ALLOW AUTHENTICATED ALL BOOKINGS" ON BOOKINGS FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "ALLOW AUTHENTICATED ALL ADMIN_NOTES" ON ADMIN_NOTES FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "ALLOW AUTHENTICATED ALL NOTIFICATIONS" ON NOTIFICATIONS FOR ALL USING (auth.role() = 'authenticated');


-- ==========================================
-- 5. SECURE FUNCTION FOR PUBLIC AVAILABILITY
-- ==========================================
-- THIS FUNCTION RUNS AS THE DATABASE OWNER (SECURITY DEFINER), BYPASSING RLS,
-- BUT IT ONLY RETURNS A BOOLEAN OR GENERIC STATUS
CREATE OR REPLACE FUNCTION GET_PUBLIC_AVAILABILITY(REQ_START_DATE DATE, REQ_END_DATE DATE)
RETURNS TABLE (
    EVENT_DATE DATE
,   IS_AVAILABLE BOOLEAN
) 
LANGUAGE SQL SECURITY DEFINER SET search_path = public
AS $$
  SELECT 
      B.EVENT_DATE,
      FALSE AS IS_AVAILABLE
  FROM 
      BOOKINGS B
  WHERE 
      B.EVENT_DATE >= REQ_START_DATE 
      AND B.EVENT_DATE <= REQ_END_DATE
      AND B.STATUS IN ('CONFIRMED', 'COMPLETED');
$$;


-- ==========================================
-- 6. SEED ADMIN USER
-- ==========================================
DO $$
DECLARE
    NEW_USER_ID UUID := uuid_generate_v4();
BEGIN
    -- 1. CREATE THE USER IN THE AUTH SCHEMA
    INSERT INTO AUTH.USERS (
        ID
    ,   INSTANCE_ID
    ,   EMAIL
    ,   ENCRYPTED_PASSWORD
    ,   EMAIL_CONFIRMED_AT
    ,   RAW_APP_META_DATA
    ,   RAW_USER_META_DATA
    ,   CREATED_AT
    ,   UPDATED_AT
    ,   ROLE
    ,   CONFIRMATION_TOKEN
    ,   EMAIL_CHANGE
    ,   EMAIL_CHANGE_TOKEN_NEW
    ,   RECOVERY_TOKEN
    )
    VALUES (
        NEW_USER_ID
    ,   '00000000-0000-0000-0000-000000000000'
    ,   'jombenitez96@gmail.com'
    ,   crypt('Fanny26!', gen_salt('bf'))
    ,   NOW()
    ,   '{"provider":"email","providers":["email"]}'
    ,   '{}'
    ,   NOW()
    ,   NOW()
    ,   'authenticated'
    ,   ''
    ,   ''
    ,   ''
    ,   ''
    );
  
    -- 2. CREATE THE REQUIRED AUTH IDENTITY
    INSERT INTO AUTH.IDENTITIES (
        ID
    ,   USER_ID
    ,   IDENTITY_DATA
    ,   PROVIDER
    ,   PROVIDER_ID
    ,   LAST_SIGN_IN_AT
    ,   CREATED_AT
    ,   UPDATED_AT
    )
    VALUES (
        uuid_generate_v4()
    ,   NEW_USER_ID
    ,   format('{"sub":"%s","email":"%s"}', NEW_USER_ID::text, 'jombenitez96@gmail.com')::jsonb
    ,   'email'
    ,   NEW_USER_ID::text
    ,   NOW()
    ,   NOW()
    ,   NOW()
    );
END $$;
